"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$username\
[](bg:gray fg:blue)\
$directory\
[](fg:gray bg:dark_gray)\
$git_branch\
$git_status\
$nodejs\
$rust\
$ruby\
$terraform\
[](fg:dark_gray bg:none)\
\n$character"""

palette = 'tokyonight_night'

[palettes.tokyonight_night]
blue = '#7aa2f7'
dark_gray = '#212736'
gray = '#3b4261'
nodejs_green = '#68a063'
ruby_red = '#cc342d'
rust_orange = '#d34516'
terraform_purple = '#7c42bc'

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

# ~/.config/starship.toml

[hostname]
ssh_only = false
format = '[ $hostname ](bg:blue fg:dark_gray)'
disabled = false

[username]
style_root = "bold fg:ruby_red bg:blue"
format = '[ $user ]($style)'

[directory]
style = "fg:blue bg:gray"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:dark_gray"
format = '[[ $symbol $branch ](fg:yellow bg:dark_gray)]($style)'

[git_status]
style = "bg:dark_gray"
format = '[[($all_status$ahead_behind )](fg:yellow bg:dark_gray)]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:nodejs_green bg:dark_gray)]($style)'

[rust]
# symbol = ""
symbol = "🦀"
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:rust_orange bg:dark_gray)]($style)'

[ruby]
symbol = ""
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:ruby_red bg:dark_gray)]($style)'

[terraform]
symbol = ""
style = "bg:dark_gray"
format = '[[ $symbol ($workspace) ](fg:terraform_purple bg:dark_gray)]($style)'
